### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by lizhenhao123** [XiongweiWu/XiongweiWu.github.io#1]
Hello, after reading your ovfoodseg, can I get the open source of the relevant code or provide some help with reproduction, such as the relevant code for data processing? Because I am an undergraduate student, my coding skills are not enough to reproduce relevant papers. I'd be very grateful if you could.

**Comment by XiongweiWu** [comment]
I feel super curious how you read my ovfoodseg paper, since I have not even released it.

**Comment by lizhenhao123** [comment]
> I feel super curious how you read my ovfoodseg paper, since I have not even released it.

During the review stage, our group reviewed this article and found it very interesting to work here. I just want to learn it further. This article is the first of its kind in open vocabulary for food segmentation and has made a lot of innovations. Therefore, I want to sincerely learn from it and continue to innovate based on your work. However, due to my limited coding ability and the upcoming Graduation is approaching and I cannot reproduce like you, so if I can get your help, I would be very grateful if possible. Acknowledgments will be included in the acknowledgments section as well as in the citations section.

**Comment by XiongweiWu** [comment]
@lizhenhao123 hi, I may release the Stage II training / eval code based on the foodlearner trained by non-food data, which obtains ~5% improvement over the baseline. For the foodlearner trained from first stage I have not kept in my personal github (You can use [lavis](https://github.com/salesforce/LAVIS) to pre-train it, but it requires very high computation cost). For the releasing details, I need to further discuss with the school since the copyright of this project belongs to SMU and I have already left the SMU.

**Comment by lizhenhao123** [comment]
Okay, thank you Dr. Wu, thank you very much. We will definitely make more innovations on this basis. Thank you for your contribution to open source. Thank you very much. What I originally meant was that the data processing part is enough. I am very grateful to be able to get the preparation part of the data set foodseg103, because we just want to use SAN to reproduce foodseg103, but I am not interested in the data processing part, such as how to convert coco data I don’t know how to replace the part that replaces the set with foodseg103. I don’t know if you can share this part of the code? Similar to the dataset part of SAN, do we need to recreate a txt file? If so, I wonder if you can give students some tips or help. If so, I would be very grateful.

> @lizhenhao123 hi, I may release the Stage II training / eval code based on the foodlearner trained by non-food data, which obtains ~5% improvement over the baseline. For the foodlearner trained from first stage I have not kept in my personal github (You can use [lavis](https://github.com/salesforce/LAVIS) to pre-train it, but it requires very high computation cost). For the releasing details, I need to further discuss with the school since the copyright of this project belongs to SMU and I have already left the SMU.

**Comment by lizhenhao123** [comment]
> @lizhenhao123 hi, I may release the Stage II training / eval code based on the foodlearner trained by non-food data, which obtains ~5% improvement over the baseline. For the foodlearner trained from first stage I have not kept in my personal github (You can use [lavis](https://github.com/salesforce/LAVIS) to pre-train it, but it requires very high computation cost). For the releasing details, I need to further discuss with the school since the copyright of this project belongs to SMU and I have already left the SMU.

谢谢您的回复，十分感谢，祝您身体健康，万事如意！

**Comment by XiongweiWu** [comment]
@lizhenhao123 You mean to generate the new few-shot sets for FoodSeg103? For this part I can share with you soon.

**Comment by lizhenhao123** [comment]
> @lizhenhao123 You mean to generate the new few-shot sets for FoodSeg103? For this part I can share with you soon.
thank you so much
